name: miggi_multi_spy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
